export { api, API_BASE_URL } from './api';
export { default as homeService, type StatsSummary } from './home.service';
export { default as statsService } from './stats.service';
export { type StatMetric as StatItem } from '../types/admin';
export { default as aboutService, type Staff } from './about.service';
export { default as programsService } from './programs.service';
export { type Program as ProgramType } from '../types/admin';
export { default as eventsService } from './events.service';
export { type Event as EventType } from '../types/admin';
export { default as galleryService } from './gallery.service';
export { type GalleryItem as Gallery, type GalleryImage, type GalleryVideo } from '../types/admin';
export { default as newsService } from './news.service';
export { type NewsArticle as News, type NewsImage, type NewsVideo } from '../types/admin';
export { default as achievementsService } from './achievements.service';
export { type Achievement } from '../types/admin';
export { default as projectsService } from './projects.service';
export { type Project as ProjectType } from '../types/admin';
export { default as contactService, type ContactMessage, type ContactSubmitData } from './contact.service';
export { default as subscriptionService, type SubscribeData, type Subscriber } from './subscription.service';
export { default as authService } from './auth.service';
